analyzer_plugin/pubspec.yaml, server_plugin/lib/src/analysis.dart, server_plugin/pubspec.yaml
Use AnalysisDomain.onResultChanged instead of onResultComputed.
Update dependency on package plugin to match that of the latest analyzer.
=> Update to work with latest analyzer.

analyzer_plugin/lib/src/resolver.dart
The newly created local variable needs to be added to the localVariables list of the enclosing element or it would cause an exception later while getting its hash code(for putting in a map) later.
Fixes 12 of the 14 failing tests.
=> Fix an exception when processing local variables in templates.

analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/test/abstract_angular.dart
Check whether an annotaion belongs to Angular 2 using the library source path. The library names for Angular 2 sources are empty because there are no library declarations in Angular 2.
=> Fix check for Angular 2 annotations.

analyzer_plugin/lib/src/angular_work_manager.dart, analyzer_plugin/test/angular_work_manager_test.dart
Note that this error was also in the analyzer source and I have a patch open for that: https://codereview.chromium.org/2454233003/
With both this and the patch in the analyzer, html template errors are kept in sync when you update dart files.
=> Monitor the correct stream of invalidations to keep views in sync

analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/tasks_test.dart
In the view building task, check for @Component without a @View and
handle it. Also make sure that the @View or @Component define a template
or templateUrl but not both. Tests included.
Changed most tests that used @View + @Component to just use @Component
since that is the primary use case. Kept two positive test cases for
@View + @Component, adding corresponding ones for simply @Component by
itself. Hopefully those are adequate for ensuring support for @View,
since the code is (at least currently) very similar for both workflows.
=> Support @Components without @Views as the default case, require template

analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/abstract_angular.dart, analyzer_plugin/test/tasks_test.dart
Plus tests.
Previous approach was overly complicated, thanks to Konstantin Shcheglov
for suggesting this much much simpler one.
A prior test with an invalid html template was now throwing this new error in addition to what it expected. In the name of "exactly one test should fail" I set that test to have a valid file.
=> Detect missing html template files in components

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/tasks_test.dart
Catch mustaches that weren't opened, and mustaches that open before
another one closes. Also change 'lastEnd' + 'offset' to 'textOffset' and
'fileOffset' since that is clearer.
Also catch more than one mustache error per text snippet in the html.
Plus tests.
=> Catch more types of unmatched mustaches

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/test/tasks_test.dart
Noticed that the error wasn't occurring inside full html templates, saw
the difference in how the dart analyzer handles html parsing and applied
it here. Saves us from getting highly involved in the dart html parser
API when the root isn't simple.
=> Template errors beyond first tag

analyzer_plugin/pubspec.yaml, analyzer_plugin/test/abstract_angular.dart, server_plugin/pubspec.yaml
Mostly just needed to hardcode the path for the frontend so we can
import a consistent version of the sdk. However, did also lose the
Errors.EMPTY_LIST constant for some reason, filled that in too.
=> Fix analyzer/frontend split dependency

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/test/resolver_test.dart
I think index=x works now as well.
Also kept support for var- last minute as I saw that it still works even
though its deprecated.
Also added assertNoErrors to the resolver tests because it helped me
debug my own changes and will probably help the next person as well.
=> Renew ngFor support with let-x instead of #x, refs #46 and #4

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/resolver_test.dart
Make validating attribute values take the directives attached to the
component. In order to prevent double matching selectors (which, as
written now, would resolve their ranges twice), store them on the
ElementInfo object.
Also rename resolveNodeNames to resolveDirectives because that's what it
does.
Originally I had done some refactoring to not require a mutation of the
ElementInfo object, but due to the nature of #localRefs, it requires
more than one pass over the AST (one to resolve the directives and load
the local vars, and then another to typecheck the expressions with the
scope finalized). Therefore I could either mutate the AST or copy
it/produce a new IR, which seems unwarranted.
Tests; some were updated because they didn't have valid usages of inputs
and not. Others are new to …
=> Issue 42 typecheck inputs

analyzer_plugin/test/mock_sdk.dart, analyzer_plugin/test/resolver_test.dart
This broke when inputs were added, and the error was revealed when the ngFor branch added 'assertNoErrors' to the test.
Use h1 instead of li because h1 is in the mock sdk already and li is not...but adding li caused new resolved ranges in many tests, which would require updating those tests to get them passing again.
Still two more tests failing from the merge, likely the same overall reason (broken by inputs branch, revealed by assertNoErrors in ngFor branch) but with a different underlying cause.
=> Fix test which used nonexist html property that the mock sdk didn't know about

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/test/resolver_test.dart
This only applies to `<template ngFor...>`, note that the sugared template
syntaxes are handled differently and don't have this problem because the
sugared attributes are handled before the other attributes are.
No longer resolve template attributes before the template directives are
resolved. Still, we have to resolve the ngFor attribute before we can
put the ngFor variables in scope. So, split that apart from the other
types of vars that are defined based on directives. In the case of
resolving attributes for a template, do the ngFor resolution later but
not too late; in the case of sugared templates, do the same order.
Edit: fixes two tests: https://travis-ci.org/dart-lang/angular_analyzer_plugin/jobs/176588080 failure caused be the addition of input validation, which were revealed …
=> Fix issue of template attrs being resolved twice, once without directives

analyzer_plugin/lib/src/model.dart, analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/mock_sdk.dart, analyzer_plugin/test/resolver_test.dart, analyzer_plugin/test/tasks_test.dart
The parseDartExpression code defines a local scope, so have it accept a
nullable EventType thing to fill in the $event var on that scope rather
than have stuff outside of that function have to set up/tear down the
scope properly.
Track the event types of html components as well as the event types of
custom components, and store those in OuputElement since they have
different methods of being discovered
=> Typecheck $event (#37) and ensure @Output are EventEmitters (#41)

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/src/selector.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/resolver_test.dart
Support for #50 two-way binding validation
validate types (as an input), assignabliity, and change the way unbound
error types are tracked. For a two-way bound input named x of type t,
check that an ouput name xChange exists which is assignable to type t.
Smarter tactic of ignoring :not()s, so that core directives work
=> Issue 50 twoway binding validation

analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/test/mock_sdk.dart, analyzer_plugin/test/tasks_test.dart
Don't take the dart:html method name and chop off the 'on', that's not
how angular does it. Instead take the @DomName('Document.oneventname')
and get just the eventname out of that.
Previous tests used 'keyUp' as a testcase, but the correct angular is
'keyup'. Note that this difference is in dart:html and was kept in
mock_sdk.dart
=> Fix for issue #77 some dom events not recognized

analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/abstract_angular.dart, analyzer_plugin/test/tasks_test.dart
Just a matter of supporting MethodDeclaration members as well, provided
each .isGetter or .isSetter. Report errors otherwise.
=> Support getters and setters with @Input and @Output refs #83

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/resolver_test.dart
Validate binding names when they are~~n't a dart identifier or~~ one of
these special bindings. Check what we can easily check with these
including:
* class.x has a valid classname for x
* class.x is bound to a boolean
* style.x has a valid css identifier for x
* style.x.y has a valid css identifier for x
* style.x.y has a valid css identifier for y (units)
* style.x.y is bound to a number
Went to validate attr.x, but if x is an invalid attr name, then [attr.x]
is an invalid attr name. And there's no typechecking to be done here, at
least, not until we try to discover specific attributes and do stuff
with that (however...even that, I think it just all becomes strings
eventually with .toString(), making there nothing to check)
Used to validate the rest were valid dart identifers, but you …
=> Support [attr.x], [class.x], [style.x], and [style.x.px] refs #82

analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/test/tasks_test.dart
Use the mostSpecificTypeArgument method API to get the stream type
regardless of the inheritance tree and generics defined within it.
=> Allow Stream<T> and subtypes of it in outputs, refs #76

analyzer_plugin/lib/src/model.dart, analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/test/resolver_test.dart, analyzer_plugin/test/tasks_test.dart
In the future, maybe there's a way to know the directive's parameters
based on how its used in the template. For now, use the upper bounds
because those are the lowest types and therefore can be relied upon in
the template, and avoids the 'T is not subtype of String' errors.
Refactoring: changed event typechecking to go off of a new type field on
InputElement so that it could be deparameterized consistently at
collection time rather than deparameterized everywhere its used. Same
for outputs, but those already had an eventType field that was used
everywhere.
Opening new issue #91 for some tricky subtleties in generic chains.
Looks like this code should some day use `instatiateToBounds` but that
will not do much typing without strong mode turned on, and has a bug
that is open in their repo.
=> Best current solution to handle all types of generic directives refs #86

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/resolver_test.dart
Previous modification (Issue 36) only impacted expressions within moustache. This change will also now impact property binding expressions. There is a quick flag to prevent false-positives on event binding expressions; this is temporary until event binding expressions are properly implemented.
=> Refactoring TRAILING_EXPRESSION error into a more logical position

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/test/mock_sdk.dart, analyzer_plugin/test/resolver_test.dart, analyzer_plugin/test/tasks_test.dart
New `ResultDescriptor` to track the outputs of `HtmlElement` separately,
all elements at resolution stage can use them. No longer tracked on the
standard HTML components (now only a few special html components, such
as body).
When resolving events, check the standard html event when there's no
match otherwise.
Altered Mock SDK to better reflect the real dart html source, namely
* HtmlElement is not the root of the inheritance tree
* BodyElement has events not on HtmlElement
* keyup event is on HtmlElement, not InputElement
* Element (parent of HtmlElement) has events
No. 1 and 4 are important for correct implementation of
`_captureAspects`. Number 3 was a mistake I'd made when adding outputs.
Number two is an edge case.
Store everything in a nicely indexed map, because that's probably …
=> Track native DOM events on componets refs #101

analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/test/resolver_test.dart, analyzer_plugin/test/tasks_test.dart
Move to a class-instantiation paradigm; instantiate the type to bounds
before building the component (still using custom instantiation logic
while issue #91 is blocked), and use that to resolve getters/setters up
the inheritance tree.
No change to the @Input() and @Output() workflows because those don't
involve inheritance.
=> Solve issue #103 generic inherited types still unresolved

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/test/resolver_test.dart
Building on issue 36
Event handlers are able to take statements instead of expressions. I've created a similar stack for resolving statements and generalized _recordExpressionResolvedRanges and _resolveDartExpression to be more generic to resolve any AstNode (expression or statement). 
Added a separate path to resolve event statements within _resolveAttributeValues. This will be refactored in another pull request.
=> Statement handlers refs #36

analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/offsetting_constant_value_visitor_test.dart, analyzer_plugin/test/tasks_test.dart, analyzer_plugin/test/test_all.dart
PR will fail to build until https://codereview.chromium.org/2586363004/ is merged.
Handle template: 'a' + 'b', etc.
Use ConstantEvaluator for most of the heavy lifting, but for things like
templates where we need to track offsets, use a special new visitor
(with tests) to pad in appropriately to match the constant expression
around operators, parens etc.
recognize when adding spaces can't fix stuff, and bail out.
=> Handle sanest and some of the crazier constant template expressions

analyzer_plugin/lib/ast.dart, analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/test/resolver_test.dart, server_plugin/lib/src/completion.dart, server_plugin/test/completion_contributor_test.dart
Suggest outputs in the middle of writing them.
Suggest events like click, mouseover, etc, all at lower priority than
other directive outputs, though ideally they would be at the same
priority on standard dom. Could adjust that later.
Tests that they are suggested at the right times at the right priority.
=> Autocomplete outputs within other outputs, and standard events.

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/test/resolver_test.dart
Missing resolution step compared to the regular resolution workflow.
Well, technically, we were missingtwo. But one of them: collecting
varibales, is not relevant to us.
This should be a good change for stability in general, though we
probably allow expression types we shouldn't like typed array list
literals that angular won't like.
=> Fix issue #204 error when '<' is in binding.

analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/test/mock_sdk.dart, analyzer_plugin/test/tasks_test.dart
Turns out that the option tag, as well as a few others, don't specify
their tagname anywhere in the source of the dartium html file we scan
to generate the standard html components, so it wasn't being recognized
as a component at all.
There's even one component in there that appears at first glance to be
an html component in the same boat, but it isn't. And there's a few
deprecated ones that are like that too. Skip those (testing the
former...the latter...that I care less about).
Just hardcoded a list, and tested that option works just to test that
my list takes effect. Could have tested the rest, but I don't usually
like it when test code and real code match up 1:1 like that would
appear.
Also modify the mock sdk to include the tested cases.
=> Fix issue #199 option value not recognized

analyzer_plugin/lib/src/converter.dart, analyzer_plugin/test/resolver_test.dart
Looks like 'value' is emptystr for templateAttributes without a value,
but valueOffset is null. Therefore later code sees the value as
existing but erroneous, and reports an error but the error can't be
hashed since it contains a null.
This is already specifically avoided inside text attributes, expression
attributes, and statement attributes. Now in template attributes too.
Of course, `<h1 *#h1></h1>` seems to cause angular to crash, but it
should actually be valid as the desugared form `<h1 template="#h1"></h1>`
is valid. (and so is the further desugared form `<template #h1><h1>...`).
But we report an error anyways: 'did you mean let?'. So while I don't
want to assert that error or a different one, I do want to assert it
doesn't crash, so that's all the test does even though 'no crash' …
=> Fix issue #213 crashing *#h1 attribute

analyzer_plugin/lib/ast.dart, analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/test/resolver_test.dart, analyzer_plugin/test/tasks_test.dart, server_plugin/lib/src/completion.dart, server_plugin/test/completion_contributor_test.dart, server_plugin/test/mock_sdk.dart
They can be used on components now and are scraped from the dartium
html source, just like standard html events.
Autocomplete them at a lower priority just like standard html events.
=> Implement issue #201 track global html attributes

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/resolver_test.dart
Not all of the dart AST is acceptable inside expressions in templates,
and some of the unacceptable ones were resulting in errors. We also
weren't reporting errors for types of things that didn't work inside
angular anyway.
Now catch:
* named arguments
* typed map & list literals (previously caused internal crash)
* anonymous function (#205)
* overriding locals (#210)
* overriding members in expressions (angular disallows this)
* symbols
* throw/rethrow
* new
* is & as
* double dot cascade operations
* this/super
* await (tests at least, already was treated as an identifier)
Also keep our pipes solution working which relied on creating
`AsExpression`s which I'm now blocking. Use the obviously synthetic
offset 0 to detect and let that through.
Fixing overriding of locals was messy. Went …
=> Fix #210 and #205 and probably more -- trying to resolve unfitting ASTs

analyzer_plugin/lib/src/selector.dart, analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/selector_test.dart, analyzer_plugin/test/tasks_test.dart
Handle :not, merge ORs into a single list (before only ever had two
selectors within any ORs), test that that all worked out.
Now reports more specific locational data when there's an error.
Don't handle :contains, basically it seems an absolute edge case that
handling would add absolutely no value yet. Since it only matches
TextInfo nodes, there are no inputs, outputs, references...basically,
the only thing I can think of doing with it is highlighting that it was
matched (because its damn mysterious) and knowing that it was matched
should we recommend removal of unused directives. Maybe there's more, I
dunno, but it seems very unnecessary.
=> Solve #43 conclusive selector support (..though not :contains yet.)

analyzer_plugin/lib/ast.dart, analyzer_plugin/lib/src/converter.dart, analyzer_plugin/test/resolver_test.dart, server_plugin/lib/src/completion.dart, server_plugin/test/completion_contributor_test.dart
Previously I had made ngFor="let x of " try to parse a statement after
"of". Unfortunately, this is not actually a valid parsing requirement
(though it does indicate an issue, that's for a linter to raise, or for
us to raise in tandem with special ngFor detection, because in a general
sense it could be valid).
Also noticed that "*structuralDirective="let x; attr; attr;" would be
reported wrong while messing with the idea of treating *deferred as
*deferred=";" to suppress the error. Left that fix in.
Once we don't report "of" itself as a syntactic error (it isn't as said
above), then we no longer have a partial expression for
DartSnippetExtractor to pick up. So instead, inside DartSnippetExtractor
we look for TextAttributes that could be intended to become
ExpressionBoundAttributes, and …
=> Fix issue #220 *deferred error. Change ngFor autocomplete strategy

analyzer_plugin/lib/src/from_file_prefixed_error.dart, analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/test/tasks_test.dart
Main use case here is being able to tell when "unresolved tag" etc
errors come up from a test file rather than production file. Without a
"from" path in that case, you can't tell.
=> Attach "from" path to template errors when "from" a strange file #109

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/src/selector.dart, analyzer_plugin/test/resolver_test.dart, analyzer_plugin/test/selector_test.dart
Handle cases like `x[y],[z]`, which doesn't actually match the tag
for `<x z` even though it matches the tag...or maybe I should say,
it matches the element but not because of the tag name.
Do this by returning not true/false, but an enumeration from
selector.match, where the possible values are no match, tag match, or
non tag match.
In the case of or selectors, don't stop on the first non tag match, in
case that a later tag match will occur. In the case of and selectors,
return tag match if any item in the match is a tag match.
=> Resolve issue #171 track tags matching complex selectors

analyzer_plugin/lib/ast.dart, analyzer_plugin/lib/plugin.dart, analyzer_plugin/lib/src/angular_work_manager.dart, analyzer_plugin/lib/src/converter.dart, analyzer_plugin/lib/src/model.dart, analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/src/selector.dart, analyzer_plugin/lib/src/tasks.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/abstract_angular.dart, analyzer_plugin/test/angular_work_manager_test.dart, analyzer_plugin/test/fuzz_test.dart, analyzer_plugin/test/resolver_test.dart, analyzer_plugin/test/selector_test.dart, analyzer_plugin/test/tasks_test.dart, server_plugin/lib/src/analysis.dart, server_plugin/lib/src/completion.dart, server_plugin/test/analysis_test.dart, server_plugin/test/completion_contributor_test.dart
In order to track transclusions, we need to look into the html
templates of child components before we can check their parents. The
trick there is that this can be cyclic.
But its not really that its cyclic, its really just that its a first
pass. We don't need to know the relationship between the views before
we get the <ng-content>s in the html file for the view. Therefore we've
split VIEWS into VIEWS1 and VIEWS2. VIEWS1 is for getting the minimum
data to build an AST to check for <ng-content> selectors. In VIEWS2 we
wire up the Views that all have ASTs and ngContent tags.
We also have ANGULAR_ASTS as a new target which takes a dart file and
builds the ASTs for each view in that dart file. It is where we parse
inline dart templates, allowing us to consolidate html parsing into a
mixin in …
=> Track, validate, and autocomplete transclusions.

analyzer_plugin/lib/src/converter.dart, analyzer_plugin/lib/src/ignoring_error_listener.dart, server_plugin/lib/plugin.dart, server_plugin/lib/src/completion.dart, server_plugin/test/completion_contributor_test.dart, server_plugin/test/completion_contributor_test_util.dart
Added the ideal replacement length & offset assertions in the tests and
went from there.
Create a new visitor to detect what should be replaced in a target, but
also let the dart completion infrastructure override that when
'extractor.dartSnippet' is not null.
Always suggest `<` in tags since we can tell intelliJ to replace those.
Also found an issue where autocompleting `blah="^"` resulted in a
`replacementLength` of 4, forgotten I had treated that as `blah="null"`
in the converter to suppress the "expected identifier" warning since we
had a later warning for the tag being empty already and didn't want to
report two.
So no longer magically insert a null which messes up completion
lengths, but do still suppress that warning using a new class
IgnoringAnalysisErrorListener. Note that I had …
=> Solve issue #223 supply completion replacement length & offset

analyzer_plugin/lib/src/angular_driver.dart
Otherwise, elements like 'div', 'a', etc aren't picked up properly.
=> Force analyis of dartium lib, not dart2js, which isn't as regularly formed.

analyzer_plugin/lib/src/angular_driver.dart, analyzer_plugin/lib/src/standard_components.dart, analyzer_plugin/test/mock_sdk.dart
Otherwise you get "MouseEvent (from dartium.dart) is not assignable to
MouseEvent (from dart2js.dart)".
Easy enough to handle its syntax, though I am worried about other
differences between the two libraries and if we'll have other
inconsistencies.
But this at least removes the obvious problem(s).
=> Go back to allowing dart2js to be used, but handle it's type of code

analyzer_plugin/lib/src/angular_driver.dart
Was going to go with the resourceprovider approach performed by FileSystemState, but I don't have a resource provider. Can get one in the future, but this should mean analysis happens one time, does nothing, and is removed from the queue.
=> Defend against files hidden by generated files

analyzer_plugin/lib/ast.dart, analyzer_plugin/lib/src/angular_driver.dart, analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/resolver_test.dart
Record resolved ranges for `x="y"` where `x` is an input or a constructor
`@Attribute`. If its an input, check that strings are assignable to it.
If not, give it its own error that hopefully explains the semi magical
situation.
=> Resolve plain attributes -- in ranges, and strchecks for inputs.

analyzer_plugin/lib/src/directive_extraction.dart, analyzer_plugin/test/resolver_test.dart
Seems like in the precense of a getter, setter.variable.type is the
getter type, not the setter's type. So use the first function argument
instead.
Related to #280
=> Get setterType by setter.parameters[0] instead of setter.variable.type

analyzer_plugin/lib/src/angular_driver.dart, analyzer_plugin/lib/starter.dart, analyzer_plugin/test/angular_driver_test.dart, analyzer_plugin/test/file_tracker_test.dart, analyzer_plugin/test/fuzz_test.dart, analyzer_plugin/test/offsetting_constant_value_visitor_test.dart, analyzer_plugin/test/resolver_test.dart, analyzer_plugin/test/selector_test.dart, analyzer_plugin/test/test_all.dart, deps/pubspec.yaml, server_plugin/test/analysis_test.dart, server_plugin/test/completion_contributor_test.dart, server_plugin/test/test_all.dart, tools/update_deps.sh
Cannot use the version we were using before. And I'm not sure how these analysis errors made it through travis, but they are bad too
=> Update test_reflective_loader, fix analyzer warnings&errors

analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/test/resolver_test.dart
`[style.width.%]` and `[style.height.%]` are allowed; but usage of % is a non width or height should still raise error.
Ref issue #281
=> Percentage use fix in style.width and style.height. Test cases added

analyzer_plugin/lib/src/angular_driver.dart, analyzer_plugin/lib/src/model.dart, analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/src/view_extraction.dart, analyzer_plugin/lib/starter.dart, playground/lib/counter_component.dart, playground/lib/overview_component.dart, server_plugin/lib/plugin.dart, server_plugin/lib/src/completion.dart, server_plugin/test/analysis_test.dart, server_plugin/test/completion_contributor_test.dart, server_plugin/test/completion_contributor_test_util.dart, server_plugin/test/mock_sdk.dart
Added support for autocompletion on .html files. Inline HTML found within .dart files still does not have support yet; will add them once plugin support is added. 
Breakdown: 
* Re-added directives into view.directives.
* Minor '.toList()' conversions to help with debugging.
* 'sendAngularCompletions()' is the primary function that will be called within the analysis_server to enable .html autocompletion.
* Contributor condensed into a single contributor; no longer separate ones for .dart-inline and .html.
* New base test case added for server tests: 'AbstractAngularTest' instead of 'AbstractAngularTaskTest'.
mock_sdk.dart is a copy and paste from analyzer component; no need for review.
=> Autocompletion fix

analyzer_plugin/lib/ast.dart, analyzer_plugin/lib/src/angular_driver.dart, analyzer_plugin/lib/src/directive_extraction.dart, analyzer_plugin/lib/src/directive_linking.dart, analyzer_plugin/lib/src/model.dart, analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/src/standard_components.dart, analyzer_plugin/lib/src/summary/format.dart, analyzer_plugin/lib/src/summary/format.fbs, analyzer_plugin/lib/src/summary/idl.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/abstract_angular.dart, analyzer_plugin/test/angular_driver_test.dart, analyzer_plugin/test/fuzz_test.dart, analyzer_plugin/test/resolver_test.dart
Validates:
- ElementRef
- TemplateRef
- Components
- Directives
- String-based let bindings (and checks property match)
- all others as errors
- property has QueryList assignability for ContentChildren
- ContentChild is only matched once
Changes:
- elements matching ContentChild of parent are counted as transcluded,
error wise
- DirectiveResolver is split into two phases, so that transclusions can
be checked _after_ inner content is directive resolved (for the sake of
ContentChild)
- added "StandardAngular" where we get certain special ClassElements
before running any other analysis, so that we can check if some random
type x is a supertype of angular's ElementRef.
- added ContentChildBindings so we can track the results of this
process to affect autocompletion suggestions, navigation, …
=> @ContentChild and @ContentChildren validation.

analyzer_plugin/lib/src/directive_linking.dart
Fix for: https://github.com/dart-lang/sdk/issues/29576#issuecomment-299958547
I've been trying to repro the issue by removing source imports before parsing - but haven't been able to do so. It's odd that the 'type'(ClassElement) could be found but the 'source' is showing up as null. 
This is a temporary fix in place, but it might cause strange errors to appear in the future since the directive-linking is affected. With this solution at least it won't cause a full-on crash.
=> Fix for source; null check added

analyzer_plugin/lib/ast.dart, analyzer_plugin/lib/src/converter.dart, analyzer_plugin/lib/src/directive_linking.dart, analyzer_plugin/lib/src/model.dart, analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/abstract_angular.dart, analyzer_plugin/test/resolver_test.dart, server_plugin/lib/src/completion.dart, server_plugin/test/analysis_test.dart, server_plugin/test/completion_contributor_test.dart, server_plugin/test/completion_contributor_test_util.dart
Complete inputs inside of template elements  …
Complete, for instance, `trackBy` inside of an ngFor.
Analyze and suggest directives that appear to want `*star` syntax.  …
If a `TemplateRef` is in the constructor, it works with star syntax.
Warn when not used with star syntax, and warn when star syntax is used
on a directive that does not have this special ctor as otherwise the
template will go unused.
Its not a foolproof system, I don't think. So detect that separately
from detection of ngIf and ngFor without stars. Especially so that in
the cases where this goes wrong, users can opt out of the error without
losing errors for those core directives' validation...and give
different messages.
Not sure what's more likely...that this expects too many things to be
used with stars, or not …
=> Autocomplete stars

new_plugin/lib/plugin.dart, server_plugin/lib/src/analysis.dart, server_plugin/lib/src/completion.dart, server_plugin/pubspec.yaml, server_plugin/test/analysis_test.dart, server_plugin/test/completion_contributor_test_util.dart
There has been another breaking change in server.
The server and plugin wire protocols both defined several types that were the same between the two (such things as AnalysisError and CompletionSuggestion). These types were previously being generated in two different places, forcing us to convert one representation to the other, even though the representations were identical (other than being two distinct classes). I have fixed that so that we now have a single definition of these types, but that means that several files now need to import these common classes.
This is my attempt to clean up after myself by updating your code appropriately.
=> Update imports after another breaking change

analyzer_plugin/lib/src/converter.dart, analyzer_plugin/lib/src/resolver.dart, analyzer_plugin/lib/tasks.dart, analyzer_plugin/test/abstract_angular.dart, analyzer_plugin/test/resolver_test.dart
Pretty large change in terms of how let- and # variables are defined and resolved as.
Resolves issues: #167  #176  #321 
Major changes:
- `let-` binding is now only allowed to be used in `<template>` bindings, throws an error otherwise.
- `#ref` now properly references `TemplateRef` object when used inside template: `<template #ref>`
- `$implicit` logic is changed. Only in the case of `ngFor` will `$implicit` be defined. Otherwise, all other `let-noValue` bindings will link to a dynamic type. In addition, let bindings with value will also automatically be defined to dynamic type. (we can possibly, in the future, resolve these types)
- Added checks for ambiguous exportAs referencing. If two directives have the same `exportAs` value and both directives are used in the same tag linked to a …
=> Fix reference vs. let logic

analyzer_plugin/lib/src/resolver.dart, new_plugin/lib/plugin.dart
Not sure what method element local variables were doing before.
Removing that code seemed to cause no changes in behavior.
Removing the driver in place for a path was simple enough.
=> Fix build: analyzer_plugin driver changes, no MethodElement locals

angular_analyzer_plugin/lib/src/angular_driver.dart, angular_analyzer_plugin/lib/src/directive_extraction.dart, angular_analyzer_plugin/lib/src/directive_linking.dart, angular_analyzer_plugin/lib/src/model.dart, angular_analyzer_plugin/lib/src/summary/format.dart, angular_analyzer_plugin/lib/src/summary/format.fbs, angular_analyzer_plugin/lib/src/summary/idl.dart, angular_analyzer_plugin/test/angular_driver_test.dart
Much of the code change is related to tracking annotations on
non-component/directive classes. Added a new member to DirectivesResult
to decrease likelihood of a non-directive being accepted as a directive
somewhere it shouldn't.
I don't currently resolve any conflicts between inherited members at
all. Waiting for confirmation of importance and strategy.
Also requires serializing non-directive angular metadata information,
and which in turn meant refactoring the serialization/deserialization a
bit.
Naming could still use some work.
=> Track -- but don't validate yet -- annotated member inheritance

angular_analyzer_plugin/lib/src/angular_driver.dart, angular_analyzer_plugin/lib/src/file_tracker.dart, angular_analyzer_plugin/test/file_tracker_test.dart, angular_analyzer_plugin/test/test_all.dart
Track file hashes the same for html/non-html, do all hashing through
FileTracker which has a salt it applies to everything. Tests that dart
signatures, html signatures, content signatures, and unit element
signatures are salted. Refactor angular driver to use file tracker's
APIs all the time.
Also looks like file tracker tests weren't running before via
test_all.dart; fixed. And it had a test that was failing (presumably,
since it wasn't running!). Fixed that too.
Salt is currently at 1 since we're on version 1. Well, two, but the
presence of the salt distinguishes that much by itself.
=> Salt hashes for version updates of analysis/summary file formats

angular_analyzer_plugin/pubspec.yaml, angular_analyzer_plugin/test/abstract_angular.dart, angular_analyzer_plugin/test/angular_driver_test.dart, angular_analyzer_plugin/test/completion_contributor_test.dart, angular_analyzer_plugin/test/completion_contributor_test_util.dart, angular_analyzer_plugin/test/element_assert.dart, angular_analyzer_plugin/test/file_tracker_test.dart, angular_analyzer_plugin/test/navigation_test.dart, angular_analyzer_plugin/test/offsetting_constant_value_visitor_test.dart, angular_analyzer_plugin/test/plugin_test.dart, angular_analyzer_plugin/test/resolver_test.dart, angular_analyzer_plugin/test/selector_test.dart
Note: some tests which checked for the exact type have been replaced with typed(any).
Most changes are just API names, however `.thenInvoke` was replaced with `.thenAnswer` which has a slightly different API.
anyObject -> typed(any)
anyInt -> typed(any).  I don't think there is a way to express anyInt in 'package:test' since they assume you are using strong mode.
EDIT:
Note that .verify seems to work much differently now.  Each time you call `called(n)` or similar it will reset the count.  This only affects one test in file_tracker_test where verify was used in a loop.
EDIT:
I am wrong about the typed api, the pattern to test for an instance of a type is
`argThat(new isInstanceOf<TypeIExpect>())`
=> Update tests to use package:test and package:mockito

angular_analyzer_plugin/lib/src/converter.dart, angular_analyzer_plugin/test/resolver_test.dart
There's at least one condition which currently causes a range error due
to an SDK bug: #30321. Should have a hard cap.
=> Add a hard cap on slicing dart in template attributes.

angular_analyzer_plugin/lib/src/resolver.dart, angular_analyzer_plugin/test/resolver_test.dart
Our example `*deferredContent` directive has an input, which fails the
test if we add it. Also, change it to `*deferred` for better
consistency.
Adding that aspect to the test, seems we can still pass our test suite
by limiting validation to NgIf. Left a comment to reenable it...likely
we can do this if the input is marked required, in the future, or we
can decide that the usage of `*deferred` in that test *is* invalid, and
change the definition/API so we can reenable this check.
=> Disable empty *starAttr validation, with tests

angular_analyzer_plugin/lib/src/resolver.dart, angular_analyzer_plugin/lib/src/standard_components.dart, angular_analyzer_plugin/test/angular_driver_test.dart, angular_analyzer_plugin/test/resolver_test.dart
Virtual template elements weren't treated as having a tag name, and
therefore weren't being matched against element name selectors of
template. Provide template tag name in this case, and a match occurs.
However, this also has the subtle effect of allowing you to bind to
`TemplateElement` properties in a star. Luckily, an `NgFor` test failed
for this reason.
Removed `TemplateElement` entirely from `StandardHtml`, so that won't
happen.
=> Match `selector: 'template[foo]` against `*foo`, `template="foo"`

angular_analyzer_plugin/lib/src/standard_components.dart, angular_analyzer_plugin/test/mock_sdk.dart, angular_analyzer_plugin/test/resolver_test.dart
The public setter (as well as the private member, which realistically
means nothing for most people) should be annotated, but it isn't. As
such, we can't get the DomName() for innerHTML as such (capitalized)
and then apply angular's map to it.
To ensure that we still _suggest_ `innerHtml`, the angular way, while
accepting `innerHTML`, the DOM way, reuse all existing methodologies
after doing a little switcharoo up front.
Luckily this is harmless for in the future when that annotation gets
fixed, but I hear it may be months and months away.
=> Fix rejection of innerHTML as an input due to missing dart:html annotation

angular_analyzer_plugin/test/angular_driver_test.dart
note: the build is expected to have one test failure from https://github.com/dart-lang/sdk/issues/30508
=> Make inheritance test ordering safe

angular_analyzer_plugin/lib/src/directive_linking.dart, angular_analyzer_plugin/test/angular_driver_test.dart
This will support covariant/contravariant inputs/outputs, and also
means that navigation will navigate to the implementation that dart
itself will use when the input/output is bound.
Not yet removing input: or output: from @Directive. I did test that it
works, but don't have good infrastructure to make that an easy unit
test. From my tests, our code works whether the definition of Directive
accepts those fields or not, so we're backwards compatible right now
which is great.
Added tests that generic base components resolve the types properly.
Had to move some tests from testing first pass directive collection, to
directive linking. First pass does not include directive inheritance.
ContentChild(ren) coming soon.
=> Reresolve inputs & outputs from parent classes to the child impls

angular_analyzer_plugin/lib/errors.dart, angular_analyzer_plugin/lib/src/angular_driver.dart, angular_analyzer_plugin/lib/src/model.dart, angular_analyzer_plugin/lib/src/resolver.dart, angular_analyzer_plugin/lib/src/standard_components.dart, angular_analyzer_plugin/test/abstract_angular.dart, angular_analyzer_plugin/test/angular_driver_test.dart, angular_analyzer_plugin/test/mock_sdk.dart, angular_analyzer_plugin/test/resolver_test.dart
For an input with a security context, allow binding to that security
context's safe type instead of the input type. For security contexts
with no sanitization available (resource urls ie iframe.src, scripts),
report an error if bound with anything but the safe type.
Style sanitization started but not completed. Looks like we don't allow
binding to [style] at all currently. Need to look into why its not part
of dart:html and what other exceptions we need to handle and how we
need to handle them. Security will likely "just work" then...some new
tests will need to be written and some comments in other tests will
need to be uncommented.
Script sanitization seems to be something entirely different?
Store security context classes on StandardAngular, and then use them to
create StandardHtml. …
=> Handle major Angular security contexts; script & style pending.

angular_analyzer_plugin/lib/src/completion_request.dart, angular_analyzer_plugin/test/angular_driver_test.dart, tools/travis.sh
Had one type error, that had to be fixed.
Also was tripping an assertion in the analyzer's autocomplete that
expressions must have parents. The solution here is perhaps too hacky,
but perhaps not. Just wrap in a virtual parenthesized expression.
Doesn't seem like a problem to pass in null for the open and close
paren tokens.
=> Fix tests running in checked mode, and make that default on travis

angular_analyzer_plugin/lib/src/angular_driver.dart
This is the majority use case for everyone.
Additionally, inside of google3 we had problems where
package:angular2/angular2.dart is still proxied and
package:angular2/security.dart is not, causing failed security lookups.
=> Try loading package:angular unless only package:angular2 is available

angular_analyzer_plugin/lib/errors.dart, angular_analyzer_plugin/lib/src/tasks.dart, angular_analyzer_plugin/test/angular_driver_test.dart
Should have been a hint all along, changed that.
Also, seems like I wrote tests for this but just expected the wrong
error. Solved.
Aaaand the implementation is fixed too, that helps. Basically, since
the OffsettingConstantEvaluator doesn't actually know everything
required to actually resolve the string value, some valid string
templates are not actually strings, but rather, "unknown." Don't report
its not a string just because of this.
The fact that we don't get the actual value in this case doesn't
matter; we won't analyze it.
=> Properly report a hint (not error) for overly complicated templates

angular_analyzer_plugin/lib/src/pipe_extraction.dart, angular_analyzer_plugin/test/angular_driver_test.dart
And add tests (was missing them before). Very simple change.
Must import analyzer/analyzer.dart because it exports the ParameterKind
class which is otherwise inside src/. A bit late to start following
this convention, but, still important to follow when we can.
=> Accept optional -- just no named -- parameters in pipe transform method

README.md, angular_analyzer_plugin/lib/errors.dart, angular_analyzer_plugin/lib/src/angular_driver.dart, angular_analyzer_plugin/lib/src/directive_extraction.dart, angular_analyzer_plugin/lib/src/directive_linking.dart, angular_analyzer_plugin/lib/src/file_tracker.dart, angular_analyzer_plugin/lib/src/resolver.dart, angular_analyzer_plugin/lib/src/summary/format.dart, angular_analyzer_plugin/lib/src/summary/format.fbs, angular_analyzer_plugin/lib/src/summary/idl.dart, angular_analyzer_plugin/lib/src/view_extraction.dart, angular_analyzer_plugin/test/angular_driver_test.dart, angular_analyzer_plugin/test/completion_contributor_test.dart, angular_analyzer_plugin/test/resolver_test.dart
Now part of the new AngularTopLevels construct. Find them at extraction
time, serialize them in summaries and deserialize (tick the salt to
invalidate old summaries), and link them in directives lists. Even
autocomplete them in attributes, and star attrs if its a template
directive.
Some potential clean ups possible after this:
- restructure the various summary types
- move pipes to angularTopLevels idea
=> Support Functional Directives (in directive lists, autocomplete)

angular_analyzer_plugin/lib/src/angular_driver.dart, angular_analyzer_plugin/lib/src/directive_linking.dart, angular_analyzer_plugin/lib/src/file_tracker.dart, angular_analyzer_plugin/lib/src/model.dart, angular_analyzer_plugin/lib/src/standard_components.dart, angular_analyzer_plugin/lib/src/summary/format.dart, angular_analyzer_plugin/lib/src/summary/format.fbs, angular_analyzer_plugin/lib/src/summary/idl.dart, angular_analyzer_plugin/lib/src/view_extraction.dart, angular_analyzer_plugin/test/abstract_angular.dart, angular_analyzer_plugin/test/angular_driver_test.dart
For list values we are able to report offsets of individual items, and
for const values we are not. Resolution is very different in this
respect and APIs used.
Track the angular standard classes which contain directives (view,
component), and use that resolution data to find annotations for the
case of const resolution -- this can be used in other cases too, like
pipes and selectors etc. It can also likely be used for optimizing the
current behavior.
New summary format to differentiate const/list strategy.
Tests that the `directives: VARIABLE` (or other const expression)
strategy works correctly.
=> Allow directives: VARIABLE, using a ResolutionStrategy of list/const.

angular_analyzer_plugin/lib/src/angular_driver.dart, angular_analyzer_plugin/lib/src/file_tracker.dart, angular_analyzer_plugin/lib/src/options.dart, angular_analyzer_plugin/test/file_tracker_test.dart, angular_analyzer_plugin/test/options_test.dart, angular_analyzer_plugin/test/plugin_test.dart
No analysis yet dependent on them, but this ensures the analysis won't
be stale once that analysis is added.
Also change 'unknownTagNames' to 'customTagNames' to reflect the
setting name in the yaml file, 'custom_tag_names' which is the better
term for what it does.
Comments about how summaries will be affected by future analysis
options and making sure they are in the right locations/are adequately
differentiable.
=> Incorporate custom_tag_names into unit signatures for summaries.

angular_analyzer_plugin/lib/ast.dart, angular_analyzer_plugin/lib/src/angular_driver.dart, angular_analyzer_plugin/lib/src/resolver.dart, angular_analyzer_plugin/test/abstract_angular.dart, angular_analyzer_plugin/test/resolver_test.dart
Inputs and outputs may be because of web components, ignore those
warnings on a tag that was entered as a custom tag.
Ensure we stil get all the rest.
=> Suppress many (but not all) errors when they occur on custom tags.

README.md, angular_analyzer_plugin/pubspec.yaml, angular_analyzer_plugin/tools/analyzer_plugin/pubspec.yaml
Many many bugfixes since, even some in angular_ast. Definitely worth
publishing now.
Instructions for loading an exact version via the self-loader method,
which is updated here to load itself at the same version (0.0.11)
=> Publish 0.0.11

angular_analyzer_plugin/lib/src/model.dart, angular_analyzer_plugin/lib/src/standard_components.dart, angular_analyzer_plugin/lib/src/view_extraction.dart, angular_analyzer_plugin/test/abstract_angular.dart, angular_analyzer_plugin/test/angular_driver_test.dart, angular_analyzer_plugin/test/navigation_test.dart, angular_analyzer_plugin/test/resolver_test.dart
Fix all tests using it, remove tests testing it specifically, and
remove it as a possibliity for the directives lookup strategy.
Remove from test angular code as well, to confirm our code will run
when that class is absent.
Doesn't yet refactor the backing View classes from lib/src/model
=> Remove all references to @View, which has been removed from angular

angular_analyzer_plugin/lib/errors.dart, angular_analyzer_plugin/lib/src/directive_linking.dart, angular_analyzer_plugin/test/abstract_angular.dart, angular_analyzer_plugin/test/angular_driver_test.dart, angular_analyzer_plugin/test/resolver_test.dart
A couple subtle things:
* deprecate the SHOULD_BE_QUERY_LIST error code but keep it. The cache
includes the message itself, so to fix it we'd have to bust the cache
which causes deep reanalysis. Next time we bust the cache we can drop
it.
* We have no testing infrastructure for different versions of our
angular version, so I can't test the case where QueryList is removed
from the source. However, its used in one place so I think that's OK.
Have a comment to help people avoid that trap.
And some basic things:
* Accept either QueryList or List
* Change all tests to use List (the preferred way now)
* Add one test to ensure QueryList still works and call it good
=> Use List instead of QueryList (though still support it, for now).

angular_analyzer_plugin/lib/src/selector.dart, angular_analyzer_plugin/test/selector_test.dart
Previously, `[x="y"]` would look for `<... x='"y"'>`. That is to say,
it expected literal quotes rather than expecting merely the value `y`
for some attr `x` via some valid html.
Split the regex for attrs into three options: no quotes (and
potentially no attrs), single, and double quotes. This allows us to
mostly keep the same Map system for making match indexes a little bit
less awful to use.
Required using some offsets off of the match index, so track that, and
use that accordingly.
=> Handle quotes in attribute selector values.

angular_analyzer_plugin/lib/errors.dart, angular_analyzer_plugin/lib/src/angular_driver.dart, angular_analyzer_plugin/lib/src/directive_linking.dart, angular_analyzer_plugin/lib/src/model.dart, angular_analyzer_plugin/lib/src/resolver.dart, angular_analyzer_plugin/lib/src/standard_components.dart, angular_analyzer_plugin/test/angular_driver_test.dart, angular_analyzer_plugin/test/resolver_test.dart
Accept (for the moment) ElementRef, Element, and HtmlElement (the
latter two being from dart:html).
Update most tests specific to ElementRef to have a copy that uses
Element. Tests that use ElementRef to check general
transclusion/content child/content children behavior which use
ElementRef have been changed to use Element.
We currently don't differentiate SVG and HTML, so we accept either type
for either case at the moment.
=> Add new options for ContentChild(ren) in prep for deprecating ElementRef

tools/travis.sh
Use the travis environment variable instead -- but still fall back to
git branch for local runs.
This only affects branches running with SDK_AT_HEAD.
=> Fix travis branch detection; git branch doesn't seem to work.

angular_analyzer_plugin/lib/src/completion.dart, angular_analyzer_plugin/test/abstract_angular.dart, angular_analyzer_plugin/test/completion_contributor_test.dart
Inside `<div *foo=" ... ">`, we look at the `Foo` directive for inputs
`fooBar`, `fooBaz`, and suggest `bar:`, and `baz:`. However, when `Foo`
has a `foo` input, we may try to suggest it at times. In these times,
it crashes because it gets the suffix (empty string) and attempts to
decapitalize the first character (there is no first character), and it
crashes.
We have no business suggesting it. That is to say, we *could* handle
the crash and suggest ':', but that would be a bogus suggestion anyway.
We already do a prefix check, simply a matter of adding an equality
check too.
=> Fix crash where we suggest something prefixed by itself, a range error.

README.md
Also remove plurality from readme which is outdated (used to be server
plugin/analysis plugin, now its just a server plugin).
fix https://github.com/dart-lang/angular_analyzer_plugin/issues/471
=> Fix #471 add status badge to README

angular_analyzer_plugin/lib/src/navigation.dart, angular_analyzer_plugin/lib/src/standard_components.dart, angular_analyzer_plugin/test/angular_driver_test.dart, angular_analyzer_plugin/test/mock_sdk.dart, angular_analyzer_plugin/test/navigation_test.dart
It's not a part of dart:html, but it works inside angular by binding to
events by name. Find its event type (FocusEvent) manually, after
performing the usual standard html resolution.
Since it doesn't have a getter, it doesn't have a range. Test that
navigation won't crash.
=> Support (focusin) and (focusout), taking care of its nonexist getter

angular_analyzer_plugin/lib/src/completion.dart, angular_analyzer_plugin/lib/src/model.dart
I forgot to rebase #482 on top of #483 before merging, where the latter
removed solo_tests that were suppressing some test failures. This means
that I missed some test failures in #482.
=> Fix failures in focusin/out support that were missed due to solo_tests

angular_analyzer_plugin/lib/plugin.dart, angular_analyzer_plugin/lib/src/angular_driver.dart, angular_analyzer_plugin/lib/src/file_tracker.dart, angular_analyzer_plugin/lib/src/options.dart, angular_analyzer_plugin/lib/src/standard_components.dart, angular_analyzer_plugin/test/abstract_angular.dart, angular_analyzer_plugin/test/angular_driver_test.dart, angular_analyzer_plugin/test/file_tracker_test.dart, angular_analyzer_plugin/test/options_test.dart, angular_analyzer_plugin/test/resolver_test.dart
```
analyzer:
plugins:
angular:
enabled: true
custom_events:
doodle:
type: DoodleEvent
path: 'package:doodle/events.dart'
poodle:
type: PoodleEvent
path: 'package:doodle/events.dart'
```
These don't yet correlate to tags, that could be next up, either
allowing a tag name in the custom_events section, or allowing
custom_events within a tag section, or both.
Still haven't fully decoupled [Options] from [FileTracker], but at
least the new hashes are *less* coupled, and I have some ideas to go
the rest of the way cleanly.
Gather the custom events inside the driver, and make it look like a
part of standard html. Track the source of the options file and the
name offsets of the custom events so that it they be supplied during
completion etc.
Currently doesn't re-resolve the custom event type. …
=> Allow custom events with custom types to be specified.

deps/pubspec.yaml
After syncing SDK_AT_HEAD, it needs an update to angular_ast version.
The master branch uses the package pubspec.yaml, and, after an upgrade of angular_ast, had to change an expectation.
That new expectation is now in SDK_AT_HEAD, but, in order to get the SDK at HEAD, it ignores that pubspec yaml in favor of this specialized one which wasn't updated and therefore its getting a version of angular_ast that fails that test which was changed before.
=> After syncing SDK_AT_HEAD, it needs an update to angular_ast version.

angular_analyzer_plugin/lib/plugin.dart
Due to bad naming (isHtml => templatesOnly), html tracking went
backwards and when cached results with navigation subscriptions were
sent out, the file was analyzed as the wrong source, and this caused
flat buffer parsing crashes.
=> Fix crash when navigation subscription is running.

angular_analyzer_plugin/lib/plugin.dart, angular_analyzer_plugin/lib/src/angular_driver.dart, angular_analyzer_plugin/lib/src/navigation.dart, angular_analyzer_plugin/test/navigation_test.dart
This is a big performance regression in IntelliJ when inside HTML (where
content info isn't as nicely cached for us by the driver). Before
serving completions, for instance, the navigation would be reading in
large files and computing their line infos which was like 90%+ of CPU
time.
By sharing the overlay, navigation is now 0.16% of CPU time and
completions are much snappier.
=> Correctness/Performance fix: Use FileContentOverlay in navigation

angular_analyzer_plugin/lib/plugin.dart, angular_analyzer_plugin/lib/src/angular_driver.dart, angular_analyzer_plugin/lib/src/notification_manager.dart
This is cleaner, and closer to the end goal state of only having one
loader architecture. It also solves a bug on windows, wherein
autocompletion fires before error resolution, which prefills the summary
but doesn't send errors over the notification manager (but does emit the
DirectivesResult over the stream). Then when error resolution comes in,
the angular driver thinks its getting a repeat result and it doesn't
bother resending errors.
=> Use results stream to send error notifications.

angular_analyzer_plugin/lib/plugin.dart, angular_analyzer_plugin/lib/src/angular_driver.dart, angular_analyzer_plugin/test/abstract_angular.dart, angular_analyzer_plugin/test/angular_driver_test.dart, angular_analyzer_plugin/test/completion_contributor_test_util.dart, angular_analyzer_plugin/test/fuzz_test.dart, angular_analyzer_plugin/test/navigation_test.dart, angular_analyzer_plugin/test/resolver_test.dart
Public members resolveHtml, resolveDart have to be atomic to be
guaranteed to work well and at the very least easy to read, reason
about, and debug. In addition, resolveHtml has an order-of-operations
requirement that it comes after all dart has been fully analyzed.
Change the requestErrors APIs (which we only used in the old API) to
request full [DirectiveResult]s, and use that everywhere that we used to
use resolve(Dart|Html), because that was made free of race conditions.
One caveat here is that everywhere resolve(Dart|Html) was used, it
required cache busting. This means that the deprecated [requestErrors]
APIs will be slower as those didn't used to, and don't need to, cache
bust. Since they're deprecated this isn't a problem.
Another note, is that we can't share a scheduler with the …
=> Make AngularDriver less prone to race conditions with smaller API.

CHANGELOG.md, angular_analyzer_plugin/lib/src/converter.dart, angular_analyzer_plugin/test/resolver_test.dart
This is not the cleanest solution from a "language theory" perspective.
I did try extending [parseEqualityExpression] to accept the new
operator, but it isn't particularly clean since equality operators have
a few micro details (allowing super==, disallowing x == y == z). Also,
since === has the same precedence as ==, they must share a loop which
means copying the lower implementation, which seemed like too much
coupling, on top of the fact that its already extending something that
will have a limited lifetime.
By replacing === with ==, we may see some strange behavior. For
instance, 'x === y === z' will highlight two characters of the second
'===' when it complains about doing equality with an equality.
But the important thing is that it doesn't matter if we butcher string
literals, and …
=> Lexically and unintelligently accept `===` by replacing it with `== `.

CHANGELOG.md, angular_analyzer_plugin/lib/src/view_extraction.dart, angular_analyzer_plugin/test/angular_driver_test.dart
Definitely possible that this solution is still a bit hairy, but this is
at least an initial step to support.
=> Fix #532 template URLs relative to parts' libraries rather than the part

CHANGELOG.md, angular_analyzer_plugin/lib/src/pipe_extraction.dart, angular_analyzer_plugin/test/angular_driver_test.dart
Looks like we just had to use a different API.
=> Fix #533 support pipes with inheritance.

CHANGELOG.md, angular_analyzer_plugin/lib/ast.dart, angular_analyzer_plugin/lib/src/completion.dart, angular_analyzer_plugin/lib/src/resolver.dart, angular_analyzer_plugin/lib/src/selector.dart
Rather than returning AttributeSelector, which we don't use, return just
the AngularElement, which we do.
This makes us able to split up the type of AttributeSelector's/things
which can lead to attributes, without having to make a subclass
relationship between all tags that mean attribute names could be
autocompleted.
=> Refactor getAttributeSelectors -> getAttributes, and return element.

CHANGELOG.md, README.md, angular_analyzer_plugin/lib/plugin.dart, angular_analyzer_plugin/tools/analyzer_plugin/pubspec.yaml
Good time to publish; we have some bugfixes for users, and once this is published we can update the setup instructions.
The changes to analysis server to reload on start will go out in the next dev release, so this is slightly ahead of that.
=> Upgrade to 0.0.15. New instructions too.

CHANGELOG.md, README.md, angular_analyzer_plugin/lib/plugin.dart, angular_analyzer_plugin/pubspec.yaml, angular_analyzer_plugin/tools/analyzer_plugin/pubspec.yaml
I've already published this to fix the broken package. We may want to rename this getter and how it shows up in the dart analyzer diagnostic version. We also may want to add a "package plugin version" field which lets users see the info I thought it was showing
=> Revert change to plugin-get-version, which is only for API version

angular_analyzer_plugin/lib/src/completion_request.dart
This is not at all obvious, but because the branch name now has SDK_AT_HEAD, it will build in a different way that uses the latest of all dependencies. So the build should now succeed, and it should be safe to merge into the special fork branch without making me unable to publish externally in the meantime.
When autocompleting a dart snippet like "x" within "{{}}", there is no
parent node and that breaks some logic in the completion engine.
Therefore we add a synthetic parenthesized ast, but previously we had
been giving null begin and end tokens.
Create begin and end tokens via the front-end synthetic classes, and
ensure to link beginToken.next to the user's dart code's beginToken.
=> Create more robust synthetic tokens for completion integration.

angular_analyzer_plugin/lib/src/completion_request.dart
SyntheticBeginToken and SyntheticToken are now exported by the analyzer.
=> Remove unnecessary dependency on front_end

angular_analyzer_plugin/lib/src/selector.dart, angular_analyzer_plugin/test/completion_contributor_test.dart, angular_analyzer_plugin/test/selector_test.dart
Note: Looking at this code, its actually working incorrectly. It should
require a value, and [x*=y] should match attributes with name [x] when
it has a value containing "y". However, I'll fix the logic in a different
CL.
=> Split wildcards into a separate class of selector.

angular_analyzer_plugin/lib/src/converter.dart
The use of _convertStatementsBoundAttribute in _convertAttributes has
a type error that the analyzer has been failing to detect due to
https://github.com/dart-lang/sdk/issues/32305.  In order to fix this
analyzer bug, we need to first fix any type errors that exist in the
wild.
This change fixes the type of _convertStatementsBoundAttribute to
match the type expected at the use site, and adds the necessary "as"
cast.
=> Fix the type of _convertStatementsBoundAttribute.

angular_analyzer_plugin/lib/src/selector.dart, angular_analyzer_plugin/test/selector_test.dart
Note: Looking at this code, its actually working incorrectly. It should
require a value, and [x*=y] should match attributes with name [x] when
it has a value containing "y". However, I'll fix the logic in a different
CL.
=> Split wildcards into a separate class of selector, share base class

CHANGELOG.md, angular_analyzer_plugin/lib/src/resolver.dart, angular_analyzer_plugin/test/resolver_test.dart
Build will fail until https://dart-review.googlesource.com/c/sdk/+/54703 is merged.
=> Fix #567 enable static references to the component class.

.gitignore, angular_analyzer_plugin/analysis_options.yaml, angular_analyzer_plugin/lib/ast.dart, angular_analyzer_plugin/lib/src/completion.dart, angular_analyzer_plugin/test/abstract_angular.dart, angular_analyzer_plugin/test/angular_driver_test.dart, angular_analyzer_plugin/test/element_assert.dart
- address a few analysis warnings
This reduces the analysis issues reported from ~130 to 32.
Also, I notice that this package depends on package:tuple. That package has not updated its version constraint to include dart 2. We may want to in-line our use of the package (the Tuple2 and Tuple4 classes) so the angular plugin doesn't break once pub is updated to be strict about sdk deps.
@MichaelRFairhurst
=> address a few analysis warnings

CHANGELOG.md, angular_analyzer_plugin/lib/src/standard_components.dart, angular_analyzer_plugin/test/mock_sdk.dart
It looks like DomName can be inferred by lowercasing the accessor name.
This is not reliable for inputs, but for events it seems to be fully
reliable.
Make the changes to the mock SDK, these changes have also been tested
against the latest real SDK. We need integration tests for this type of
thing.
Fix #591
=> Fix (click) issues: Find events without @DomName, removed from dart:html

angular_analyzer_plugin/lib/ast.dart, angular_analyzer_plugin/test/mock_sdk.dart, angular_analyzer_plugin/test/navigation_test.dart, angular_analyzer_plugin/test/resolver_test.dart, angular_analyzer_plugin/test/selector_test.dart
- ignore some deprecated_member_use warnings in test files
- remove an unused import
- don't use the deprecated `strongMode` flag
@MichaelRFairhurst
=> address a few analysis nits

angular_analyzer_plugin/lib/src/converter.dart
This unblocks the anlayzer from switching the default parser. With the
default constructor, we can get a different instance of parser which
expects a different token stream.
=> Use non-fasta parser for statements (we already do for expressions)

CHANGELOG.md, README.md, angular_analyzer_plugin/lib/errors.dart, angular_analyzer_plugin/lib/src/angular_driver.dart, angular_analyzer_plugin/lib/src/ng_expr_parser.dart, angular_analyzer_plugin/lib/src/pipe_extraction.dart, angular_analyzer_plugin/lib/src/resolver.dart, angular_analyzer_plugin/test/resolver_test.dart
Some issues with pipe parsing offsets, and deserialization fixed.
Otherwise, we stick the pipe name & args into the AST properties, and
our already existing override of ResolverVisitor can find the synthetic
nodes for pipes and set the propagated type accordingly.
Haven't yet handled arguments -- I likely will run into issues where the
argument expressions need to be hit by each of the visitors. So I may be
better off doing a synthetic function call node that's treated
specially, rather than the previous cast technique which was more for
making an AST node that would result in the right analysis. That's no
longer necessary if we're hijacking analysis, and we want the children
of the pipe (when the pipe has arguments) to be typechecked safely which
means its probably best to make them …
=> First pass at pipe support, check return type of pipes.

CHANGELOG.md, angular_analyzer_plugin/lib/src/converter.dart, angular_analyzer_plugin/lib/src/resolver.dart, angular_analyzer_plugin/test/resolver_test.dart
Also refactored `converter.dart` to share opening/close (name)span logic
across the various special tag types (`<normal>`, `<template`,
`<ng-content>`, `<ng-container>`.
Add an assert that all `AstNode`s get matched so this doesn't
transparently happen again as new AngularAst nodes get added.
=> Support `<ng-container>` properly.

angular_analyzer_plugin/lib/errors.dart, angular_analyzer_plugin/lib/src/ng_expr_parser.dart, angular_analyzer_plugin/lib/src/resolver.dart, angular_analyzer_plugin/test/resolver_test.dart
- Don't use tuple
- Ambiguous pipe error message
- replace `parseIdentifierList().first` with the intended,
`parseSimpleIdentifier()`
- unnecessary null check
=> Feedback from Paul: Don't use tuple, ambiguous pipes, etc

angular_analyzer_plugin/lib/src/resolver.dart
This is needed due to the change in the ErrorVerifier constructor in
https://github.com/dart-lang/sdk/commit/8a2cfd86139c58c3378d903d76c43663c1c61b29.
=> Modify AngularErrorVerifier to pass InheritanceManager2 to analyzer.

angular_analyzer_plugin/lib/src/resolver.dart
The corresponding parameter was removed in
https://github.com/dart-lang/sdk/commit/1bceca91b06ac7311e92cd0da0c29b9c8f09c189.
=> Remove argument in CompilationUnitElementImpl constructor invocation.

angular_analyzer_plugin/lib/src/resolver.dart
This is needed to account for the changes to ErrorVerifier in
https://github.com/dart-lang/sdk/commit/fab5d0a50d1f26d3b7e1a7596707bc09b9a49b33.
=> Remove reference to InheritanceManager from AngularErrorVerifier.

angular_analyzer_plugin/lib/src/resolver.dart, angular_analyzer_plugin/test/abstract_angular.dart, angular_analyzer_plugin/test/resolver_test.dart
Work required on the analyzer side to remove `AngularErrorVerifier` and
`AngularResolver`, but this now decouples most of the rest of the behavior
so that removing the former should be simple. Harder will be removing
pipes so that `AngularResolver` can be removed, but that's in the works
too.
=> Change behavior to not override analyzer classes where not necessary.

angular_analyzer_plugin/lib/src/model.dart, angular_analyzer_plugin/lib/src/resolver.dart, angular_analyzer_plugin/test/resolver_test.dart
Previous non-error tests didn't actually assert no errors were reported,
only that the elements were resolved. That worked under the previous
approach where the library scope was restricted, but that doesn't work
under the new aproach where resolution occurs regardless of the export
error.
After enabling the export error, the biggest issues found were:
* summarized ExportedIdentifier has '' for prefix, not null, when
missing
* identifer.name on a PrefixedIdentifier yields prefix.suffix rather
than just suffix.
One other edge case bug remained (`prefixed.topLevelFn()`), and then
added some tests for other edge cases, and did some other minor
refactoring like introducing new locals for better type promotion.
=> Fix issues in not-exported errors, more tests.

angular_analyzer_plugin/lib/src/standard_components.dart
The non-proto security code was working, but the proto security code for resource URLs was not. Turns out there's an inconsistency here that breaks the abstraction.
=> Lookup TrustedResourceUrlProto instead of SafeResourceUrlProto

angular_analyzer_plugin/lib/src/resolver.dart
The cast refers to a private class that is being renamed. Removing the cast doesn't have any effect because the invoked method only requires a `TypeProvider`.
=> Remove an unnecessary and problematic cast

angular_analyzer_plugin/lib/plugin.dart, angular_analyzer_plugin/lib/src/completion.dart, angular_analyzer_plugin/lib/src/directive_linking.dart, angular_analyzer_plugin/lib/src/navigation.dart, angular_analyzer_plugin/lib/src/standard_components.dart, angular_analyzer_plugin/test/abstract_angular.dart, angular_analyzer_plugin/test/angular_driver_test.dart, angular_analyzer_plugin/test/element_assert.dart, angular_analyzer_plugin/test/mock_sdk.dart, angular_analyzer_plugin/test/plugin_test.dart, angular_analyzer_plugin/test/selector_test.dart
2.1.0 stable does not catch declaration casts when implicit downcasts
are disabled, which is when I migrated this project and turned that flag
on.
Fix for 2.1.1-dev.1 which does not even accept declaration casts.
=> Fix declaration casts, now that implicit downcasts are off.

angular_analyzer_plugin/test/completion_contributor_test_util.dart
The corresponding getter was removed from analyzer_plugin in
https://github.com/dart-lang/sdk/commit/5e2529c82e11150dbc2448f0f43aa4fcea16177b
=> Remove importUri from test.

angular_analyzer_plugin/test/resolver_test.dart
These tests expecting the old error code now fail, fixed.
=> Use new code UNDEFINED_PREFIXED_NAME
