dart-lang/angular_analyzer_plugin

- analyzer_plugin/lib/src/angular_work_manager.dart
- analyzer_plugin/lib/src/model.dart
- analyzer_plugin/lib/src/resolver.dart
- analyzer_plugin/lib/src/tasks.dart
- analyzer_plugin/lib/tasks.dart
- analyzer_plugin/test/abstract_angular.dart
- analyzer_plugin/test/angular_work_manager_test.dart
- analyzer_plugin/test/element_assert.dart
- analyzer_plugin/test/mock_sdk.dart
- analyzer_plugin/test/tasks_test.dart
- server_plugin/lib/src/analysis.dart
- server_plugin/test/analysis_test.dart
- server_plugin/test/mock_sdk.dart
Cleanup all deprecated imports.
Add missing methods from interfaces.
Fixe server_plugin tests and some of analyzer_plugin tests.
> chore: Cleanup analyzer warnings/hints.

- analyzer_plugin/lib/src/resolver.dart
- analyzer_plugin/test/resolver_test.dart
Seems like this bug maybe won't get handled over night, so solving it
with this cleaner solution.
> Catch the error from dart:html bug #44 with tests. Refs #33

- analyzer_plugin/lib/src/resolver.dart
- analyzer_plugin/test/resolver_test.dart
Pretty easy after adding let-x in ngFor support (#46), so this is added to
that branch.
> Support ref-x in addition to #x (github ticket #45)

- analyzer_plugin/test/resolver_test.dart
Could have sworn I saw this fail. I must have misinterpreted the error.
Still, can keep this in to ensure it keeps working in the future since I wrote it anyway.
> Test for issue #61..was not an issue but still catch regressions

- analyzer_plugin/lib/src/model.dart
- analyzer_plugin/lib/src/resolver.dart
- analyzer_plugin/lib/src/strings.dart
- analyzer_plugin/lib/src/tasks.dart
- analyzer_plugin/lib/tasks.dart
- analyzer_plugin/pubspec.yaml
- analyzer_plugin/test/element_assert.dart
- analyzer_plugin/test/mock_sdk.dart
- analyzer_plugin/test/resolver_test.dart
- analyzer_plugin/test/tasks_test.dart
A lot to look through here...have two commits with more detailed explanations.
> Issue 38 track output fields

- README.md
Based on the angular cheatsheet here: https://angular.io/docs/dart/latest/guide/cheatsheet.html
> Update readme.md to include feature graph

- .travis.yml
- analyzer_plugin/pubspec.yaml
- server_plugin/pubspec.yaml
Pub errors, hope this solves them.
> Try fixing travis by using latest dart sdk

- analyzer_plugin/pubspec.yaml
- server_plugin/pubspec.yaml
We will merge this once we have locked down our dogfood release. :)
> Don't Yet Merge! Tick versions to 0.0.1 in pubspecs

- analyzer_plugin/.analysis_options
- analyzer_plugin/lib/src/resolver.dart
- analyzer_plugin/lib/src/tasks.dart
- analyzer_plugin/test/mock_sdk.dart
- server_plugin/.analysis_options
- tools/travis.sh
> Mike strong fixes

- analyzer_plugin/lib/src/tasks.dart
Forgot to commit these, just noticed them
> Format fixes

- .gitignore
- .travis.yml
- README.md
- deps/pubspec.yaml
- server_plugin/test/mock_sdk.dart
- tools/get_deps.sh
- tools/travis.sh
- tools/update_deps.sh
Scripted way of downloading deps, and rolling them up into .packages.
Why am I doing this? This feels absolutely horrible and I wish I could
just use pub.
> Use sdk packages file

- analyzer_plugin/lib/src/tasks.dart
- analyzer_plugin/test/tasks_test.dart
- server_plugin/test/analysis_test.dart
problem was null 'setterRange' and 'getterRange' when using `@Input` and `@Output`
> Fix null pointer in navigation contributor refs #120

- server_plugin/bin/make_snapshot
This was in my local change and got committed on accident. Rolling back.
> Fix make_snapshot script

- analyzer_plugin/pubspec.yaml
- server_plugin/pubspec.yaml
We'll merge this once we're ready
> Prepare version tick to 0.0.2

- analyzer_plugin/lib/src/tasks.dart
- analyzer_plugin/test/fuzz_test.dart
Also fixed an easy edge case inside lib/src/tasks.dart.
Adds, removes, or reorganizes characters or lines within dart and html
files. Also grabbed random code chunks from the SDK and the
angular2_components library to throw in at random spots.
Already revealed a few bugs, now that its fairly settled I'm going to
leave this running for a good long while and see what it turns up.
> Fuzz tester generating random dart and html templates

- README.md
Marked a lot of items as NA that I think are NA.
Marked our autocompletion work.
Noted that build is broken
> Readme updates for jan 2017

- analyzer_plugin/pubspec.yaml
- server_plugin/pubspec.yaml
Want to get #249 merged before I merge this though
> tick versions before committing big refactor

- analyzer_plugin/lib/src/angular_driver.dart
dependent upon https://codereview.chromium.org/2828103002/
> Remove contextRoot, won't be required in master soon, and breaks dev

- analyzer_plugin/lib/src/angular_driver.dart
- analyzer_plugin/lib/src/converter.dart
- analyzer_plugin/pubspec.yaml
fixes #295 
There are some SDK packages that suffer from the same issue after running `tools/get_deps.sh`. This is only half of the fix.
> update dependencies to point to the right place

- server_plugin/test/analysis_test.dart
Fixes issue of travis failing.
> Fix server tests failing

- analyzer_plugin/lib/src/directive_extraction.dart
- analyzer_plugin/lib/tasks.dart
- analyzer_plugin/test/angular_driver_test.dart
> Change event emitter to stream

- analyzer_plugin/lib/ast.dart
- analyzer_plugin/lib/src/angular_driver.dart
- playground/lib/overview_component.html
- server_plugin/lib/src/completion.dart
- server_plugin/test/completion_contributor_test.dart
First iteration of plain text attribute completion.
Doesn't include global angular attributes yet.
> Plain attribute autocompletion

- analyzer_plugin/lib/src/angular_driver.dart
- analyzer_plugin/test/abstract_angular.dart
- server_plugin/test/analysis_test.dart
Fix path for byte_store.dart; fixes travis.
> Fix pathing for byte_store

- analyzer_plugin/lib/ast.dart
- analyzer_plugin/lib/src/converter.dart
- analyzer_plugin/lib/src/directive_extraction.dart
- analyzer_plugin/lib/src/model.dart
- analyzer_plugin/lib/src/selector.dart
- analyzer_plugin/lib/tasks.dart
- analyzer_plugin/test/resolver_test.dart
Code will be broken temporarily until this is merged.
> Remove redundant let error

- README.md
Pro tip: after reviewing diff, go to https://github.com/MichaelRFairhurst/angular2-dart-analyzer/blob/2e4881082e6675ef4233686079ba294cd4f6d04c/README.md to see how it looks
> Add exports and @deferred to readme, make an editors section, other updates

- analyzer_plugin/lib/src/ng_expr_parser.dart
> parser fix

- README.md
I got validation messages, but wasn't able to see any code completion etc. (though I don't have any real projects so don't totally understand what should/shouldn't work).
> Add VS Code to editor list.

- angular_analyzer_plugin/lib/src/file_tracker.dart
essentially, bust the cache for those switching to the pipes summaries
> Tick salt for pipes

- angular_analyzer_plugin/lib/src/angular_driver.dart
- angular_analyzer_plugin/lib/src/directive_extraction.dart
- angular_analyzer_plugin/lib/src/directive_linking.dart
- angular_analyzer_plugin/lib/src/model.dart
- angular_analyzer_plugin/lib/src/resolver.dart
- angular_analyzer_plugin/test/abstract_angular.dart
- angular_analyzer_plugin/test/angular_driver_test.dart
Doesn't actually introduce any new behavior, yet. But the ability to add FunctionalDirectives -- in theory -- will work from here.
> Refactor model to support functional directives

- angular_analyzer_plugin/lib/src/angular_driver.dart
- angular_analyzer_plugin/lib/src/file_tracker.dart
- angular_analyzer_plugin/lib/src/from_file_prefixed_error.dart
- angular_analyzer_plugin/lib/src/summary/format.dart
- angular_analyzer_plugin/lib/src/summary/format.fbs
- angular_analyzer_plugin/lib/src/summary/idl.dart
- angular_analyzer_plugin/test/angular_driver_test.dart
Requires more summary data, so also have to tick the summary salt.
> Change file-prefixed errors for "weird" include paths to be clearer

- tools/travis.sh
I'll likely keep one branch that's in sync with the SDK at head. To
maintain it, I'll make new PRs to merge in.
For that reason, go off of branch name to decide whether or not to
leave the script functionally working as is (which uses the latest), or
whether to run pub get to avoid having to work against the latest sdk
packages at all times.
> Test with pub in travis, except for specific branches.

- angular_analyzer_plugin/lib/errors.dart
- angular_analyzer_plugin/lib/src/angular_driver.dart
- angular_analyzer_plugin/lib/src/completion.dart
- angular_analyzer_plugin/lib/src/directive_linking.dart
- angular_analyzer_plugin/lib/src/model.dart
- angular_analyzer_plugin/lib/src/resolver.dart
- angular_analyzer_plugin/lib/src/standard_components.dart
- angular_analyzer_plugin/test/abstract_angular.dart
- angular_analyzer_plugin/test/angular_driver_test.dart
- angular_analyzer_plugin/test/completion_contributor_test.dart
- angular_analyzer_plugin/test/resolver_test.dart
- tools/travis.sh
will be rolling SDK_AT_HEAD into google3 soon, want to make sure SDK_AT_HEAD is up to date with master.
> Sync master into SDK_AT_HEAD

- .travis.yml
- angular_analyzer_plugin/lib/src/directive_linking.dart
- angular_analyzer_plugin/test/angular_driver_test.dart
- tools/check_no_solo_tests.sh
Check for solo_tests during travis build so this doesn't happen again.
Fixes themselves are mostly simple/harmless.
> Remove (and check for) stray solo_tests. Fix broken skipped tests.

- .travis.yml
- angular_analyzer_plugin/lib/plugin.dart
- angular_analyzer_plugin/lib/src/angular_driver.dart
- angular_analyzer_plugin/lib/src/completion.dart
- angular_analyzer_plugin/lib/src/directive_linking.dart
- angular_analyzer_plugin/lib/src/file_tracker.dart
- angular_analyzer_plugin/lib/src/model.dart
- angular_analyzer_plugin/lib/src/navigation.dart
- angular_analyzer_plugin/lib/src/options.dart
- angular_analyzer_plugin/lib/src/resolver.dart
- angular_analyzer_plugin/lib/src/standard_components.dart
- angular_analyzer_plugin/pubspec.yaml
- angular_analyzer_plugin/test/abstract_angular.dart
- angular_analyzer_plugin/test/angular_driver_test.dart
- angular_analyzer_plugin/test/completion_contributor_test.dart
- angular_analyzer_plugin/test/file_tracker_test.dart
- angular_analyzer_plugin/test/mock_sdk.dart
- angular_analyzer_plugin/test/navigation_test.dart
- angular_analyzer_plugin/test/options_test.dart
- angular_analyzer_plugin/test/resolver_test.dart
- tools/check_no_solo_tests.sh
All features here have been reviewed before.
> Procedural PR to make the SDK_AT_HEAD branch contain new features before a sync

- angular_analyzer_plugin/test/completion_contributor_test.dart
Test that the fix to analyzer_plugin fixes the corresponding issue in the angular plugin.
> Autocomplete dynamic fix

- angular_analyzer_plugin/lib/plugin.dart
- angular_analyzer_plugin/lib/src/angular_driver.dart
- angular_analyzer_plugin/test/abstract_angular.dart
- old_plugin_loader/lib/starter.dart
Confirmed it works on both Linux and Windows, thanks Brian!
> Use resourceProvider for getting sources to work on windows

- CHANGELOG.md
- angular_analyzer_plugin/lib/src/facade/exports_compilation_unit_element.dart
- angular_analyzer_plugin/lib/src/facade/exports_import_element.dart
- angular_analyzer_plugin/lib/src/facade/exports_library_element.dart
- angular_analyzer_plugin/lib/src/resolver.dart
- angular_analyzer_plugin/pubspec.yaml
- deps/pubspec.yaml
Now should be ready to test...
> Upgrade analyzer_plugin

- CHANGELOG.md
- angular_analyzer_plugin/pubspec.yaml
- angular_analyzer_plugin/tools/analyzer_plugin/pubspec.yaml
Will also wait for https://github.com/dart-lang/angular_analyzer_plugin/pull/513 before merge
> Publish 0.0.14

- angular_analyzer_plugin/lib/src/selector.dart
Curious your thoughts on if this is an improvement or if there's a better way to improve it.
> Refactor selector regex to parse operator and be easier to maintain

- playground/lib/bubbled_directive.dart
- playground/lib/counter_component.dart
- playground/lib/overview_component.dart
I had updated the packages versions but forgot to commit these changes to the imports etc.
> Fix playground to use latest angular

- CHANGELOG.md
- angular_analyzer_plugin/lib/src/selector.dart
- angular_analyzer_plugin/test/selector_test.dart
> Fix 528 css startswith selector

- CHANGELOG.md
- angular_analyzer_plugin/lib/src/angular_driver.dart
- angular_analyzer_plugin/lib/src/options.dart
- angular_analyzer_plugin/pubspec.yaml
- angular_analyzer_plugin/test/navigation_test.dart
- tools/travis.sh
Most of this is stuff that could have been done with .whereType(), but I
also still have to have it work with dart 1 so I can't use that yet.
> Support dart 2

- angular_analyzer_plugin/test/file_tracker_test.dart
- angular_analyzer_plugin/test/navigation_test.dart
- old_plugin_loader/lib/starter.dart
- tools/travis.sh
OK, if I make one PR for both commits, hopefully we can see travis turn green and it will be more fun to LGTM it! :)
> Fix travis build in one pr

- angular_analyzer_plugin/lib/src/completion.dart
- angular_analyzer_plugin/test/abstract_angular.dart
Seems extra difficult to keep travis green lately!
> Format again with dev.67

- CHANGELOG.md
- angular_analyzer_plugin/lib/src/model.dart
- angular_analyzer_plugin/test/angular_driver_test.dart
> Fix issue with dynamic pipe argument.

- tools/check_no_solo_tests.sh
This runs on travis, but was too limited before!
> Catch @soloTest in addition to solo_test

- CHANGELOG.md
- angular_analyzer_plugin/lib/src/view_extraction.dart
> Fix issue for windows creating a corrupt URI

- CHANGELOG.md
- angular_analyzer_plugin/lib/src/angular_driver.dart
- angular_analyzer_plugin/lib/src/file_tracker.dart
- angular_analyzer_plugin/test/file_tracker_test.dart
> Replace unit hash with unit signature
